# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DxKq6poLrrgCwG76nBcokuxLaqQj_AEI
"""

def kasallik_tashxisiga_qarab_shifokor_koruvi(belgi):
  if belgi=="Umumiy sog'liq muammolari, infeksiyalar, surunkali kasalliklar (masalan, diabet, gipertoniya), allergiyalar va boshqa umumiy kasalliklar boʼlsa":
     return "terapevt umumiy shifokorga murojaat qiling"
  elif belgi=="Bolalar va o'smirlarning sog'lig'i, immunizatsiya, o'sish va rivojlanish muammolari, bolalarda uchraydigan kasalliklar boʼlsa":
     return "pediatrga murojaat qiling"
  elif belgi=="Yurak va qon tomir tizimi kasalliklari boʼlsa":
     return "kardiologga murojaat qiling"
  elif belgi=="Nerv tizimi kasalliklari boʼlsa":
     return "neyrologga murojaat qiling"
  else:
     return "shifoxonaga boring"
belgi=input("Kasallik belgisini kiriting")
natija=shifokor_nomi(belgi)
print(natija)